# Generated by Django 2.2.7 on 2020-01-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usernameorhashtag', models.CharField(max_length=200)),
                ('since', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.TextField()),
                ('tweet_id', models.IntegerField()),
                ('tweet_length', models.IntegerField()),
                ('tweet_created_at', models.DateTimeField()),
                ('tweet_source', models.CharField(max_length=200)),
                ('tweet_favorite_count', models.IntegerField()),
                ('tweet_retweet_count', models.IntegerField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TwiSenApp.Post')),
            ],
        ),
    ]
