# Generated by Django 2.2.7 on 2020-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwiSenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='since',
            field=models.DateField(default=None),
        ),
    ]
