# Generated by Django 2.2.7 on 2020-01-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwiSenApp', '0002_auto_20200112_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='since',
            field=models.DateField(blank=True),
        ),
    ]
