# Generated by Django 2.2.7 on 2020-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwiSenApp', '0005_auto_20200112_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
